name: com_cingulo_sample
description: A sample boilerplate Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  analyzer: ^0.36.4
  pedantic: ^1.7.0
  package_info: ^0.4.0+10
  fluro: ^1.5.1
  rxdart: ^0.22.4
  dio: ^3.0.7
  flutter_secure_storage: ^3.3.1+1
  url_launcher: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  inject_generator:
    path: ./vendor/inject.dart/package/inject_generator
  inject:
    path: ./vendor/inject.dart/package/inject
  build_runner: ^1.7.1

flutter:
  uses-material-design: true
